In [170]:
import pandas as pd
import numpy as np


OHE or Nominal encoding

disadvantage:

1)for feature having many categories , it crete too many new features as the number of category

2)Sparse matrix get created: overfitting

In [171]:
from sklearn.preprocessing import OneHotEncoder

In [172]:
df=pd.DataFrame({'color':['red','green','blue','red','green']})
df

color
0    red
1  green
2   blue
3    red
4  green

In [173]:
#create an instance of one hot encoder
encoder=OneHotEncoder()
#perform fit and transform
encoded=encoder.fit_transform(df)
encoded

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [174]:
arr=encoded.toarray()
print(arr)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [175]:
df_encoded=pd.DataFrame(arr,columns=encoder.get_feature_names_out())
df_encoded

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0
4         0.0          1.0        0.0

In [176]:
pd.concat([df,df_encoded],axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1  green         0.0          1.0        0.0
2   blue         1.0          0.0        0.0
3    red         0.0          0.0        1.0
4  green         0.0          1.0        0.0

In [177]:
encoder.transform([['blue']]).toarray()

c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

ON tips dataset  :

on day feature

In [178]:
import seaborn as sns

In [179]:
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [180]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
df_day=pd.DataFrame(df['day'],columns=['day'])
encoded=encoder.fit_transform(df_day)
encoded

<244x4 sparse matrix of type '<class 'numpy.float64'>'
	with 244 stored elements in Compressed Sparse Row format>

In [181]:
arr=encoded.toarray()

In [182]:
df_encoded=pd.DataFrame(arr,columns=encoder.get_feature_names_out())
df_encoded

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [183]:
encoder.transform([['Sun']]).toarray()

c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 0.]])

In [184]:
pd.concat([df[['total_bill','tip','sex','smoker','day']],df_encoded,df[['time','size']]],axis=1)

total_bill   tip     sex smoker   day  day_Fri  day_Sat  day_Sun  \
0         16.99  1.01  Female     No   Sun      0.0      0.0      1.0   
1         10.34  1.66    Male     No   Sun      0.0      0.0      1.0   
2         21.01  3.50    Male     No   Sun      0.0      0.0      1.0   
3         23.68  3.31    Male     No   Sun      0.0      0.0      1.0   
4         24.59  3.61  Female     No   Sun      0.0      0.0      1.0   
..          ...   ...     ...    ...   ...      ...      ...      ...   
239       29.03  5.92    Male     No   Sat      0.0      1.0      0.0   
240       27.18  2.00  Female    Yes   Sat      0.0      1.0      0.0   
241       22.67  2.00    Male    Yes   Sat      0.0      1.0      0.0   
242       17.82  1.75    Male     No   Sat      0.0      1.0      0.0   
243       18.78  3.00  Female     No  Thur      0.0      0.0      0.0   

     day_Thur    time  size  
0         0.0  Dinner     2  
1         0.0  Dinner     3  
2         0.0  Dinner     3  
3         0.0  Dinner     2  
4         0.0  Dinner     4  
..        ...     ...   ...  
239       0.0  Dinner     3  
240       0.0  Dinner     2  
241       0.0  Dinner     2  
242       0.0  Dinner     2  
243       1.0  Dinner     2  

[244 rows x 11 columns]